version: "3"
services:
  web:
    # chạy 5 instance service "web",10%CPU, tự động restart nếu failed
    image: sunlight4d/ubuntu_nodejs:part1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet: