/*
CREATE TABLE IF NOT EXISTS tblList (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(40) NOT NULL CHECK (name <> ''),
    priority    integer NOT NULL,
    description text,
    duedate   date NOT NULL    
);
*/

const User = sequelize.define('user', {
  id: {
    type: Sequelize.STRING
  },
  name: {
    type: Sequelize.STRING
  }
});

// force: true will drop the table if it already exists
User.sync({force: true}).then(() => {
  // Table created
  return User.create({
    firstName: 'John',
    lastName: 'Hancock'
  });
});