/*
CREATE TABLE IF NOT EXISTS tblTask (
  id      integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
  listId  integer REFERENCES tblList(id),
  name    varchar(40) NOT NULL CHECK (name <> ''),
  isFinished boolean
);
*/
import { sequelize } from '../sequelize';
const Sequelize = require('sequelize');

export const Task = sequelize.define('tblTask', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true
  },
  listId: {
    type: Sequelize.INTEGER
  },
  name: {
    type: Sequelize.STRING
  },
  isFinished: {
    type: Sequelize.BOOLEAN
  }  
});
